export const GET_POPULAR_SERIES = "GET_POPULAR_SERIES";
export const GET_TOP_RATED_SERIES = "GET_TOP_RATED_SERIES";
export const GET_SERIES_ID = "GET_SERIES_ID";
export const GET_SERIES_NAME = "GET_SERIES_NAME";
export const GET_SERIES_GENRES = "GET_SERIES_GENRES";
