export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_MOVIE_ID = "GET_MOVIE_ID";
export const GET_MOVIES_NAME = "GET_MOVIES_NAME";
export const GET_MOVIES_GENRES = "GET_MOVIES_GENRES";
